name:                entranceBE
version:             0.1.0.0
homepage:            https://github.com/githubuser/entranceBE#readme
license:             MIT
author:              Author name here
maintainer:          example@example.com
copyright:           2019 Futurice GmbH
category:            Web
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - persistent-mongoDB

executables:
  entranceBE:
    source-dirs:      src
    main:             Main.hs
