name:                entranceBE
version:             0.1.0.0
homepage:            https://github.com/githubuser/entranceBE#readme
license:             MIT
author:              Author name here
maintainer:          example@example.com
copyright:           2019 Futurice GmbH
category:            Web
extra-source-files:
  - README.md

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - mongoDB
  - mtl
  - persistent
  - persistent-mongoDB
  - persistent-template
  - servant
  - servant-server
  - template-haskell
  - text
  - time >= 1.9.2
  - unordered-containers
  - uri
  - wai
  - wai-cors
  - wai-logger
  - warp

default-extensions:
  - DataKinds
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedStrings
  - ScopedTypeVariables
  - TypeApplications
  - TypeFamilies
  - TypeOperators

ghc-options: -Wall -Wcompat -Widentities -Wincomplete-record-updates -Wincomplete-uni-patterns -Wpartial-fields -Wredundant-constraints -O2

executables:
  entranceBE:
    source-dirs:      src
    main:             Main.hs
